### ISSUE TITLE
consider yaml config implementation

### ISSUE THREAD

**Issue by whilei** [ETCDEVTeam/go-schroedinger#1]
Considering something like...

```yaml
pkgtests:
  - pkg: "github.com/ETCDEVTeam/go-schroedinger..."
    rerun:
      anyFailing: false
      onlyFailing:
      - name: "TestCat"
        trialsAllowed: 23
      -
```

Pros:
 - allow only "whilelisted" tests to be rerun in case of failure
 - extensible and customizable configurations per registered nondeterministic test
 - option for explicit listing of nondeterministic tests

Cons:
 - adds a significant layer of complexity to configuration decisions... is this level of customization and detail really necessary?

Questions:
 - would this co-exist w/ existing simple plain-text file implementation?
